import "@radix-ui/themes/styles.css";
import "./globals.css";
import "./theme-config.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            suppressHydrationWarning={true} //surpress hydration mismatch warning
            data-qb-installed="true"
            className={`inter.variable ${inter.className}`}
        >
            <body>
                <Theme accentColor="orange" radius="none">
                    <Navbar />
                    <main className="p-4">{children}</main>
                </Theme>
            </body>
        </html>
    );
}
